current_portfolio:
  - ticker: DFUS
    value: 729.86
  - ticker: DFAI
    value: 316.16
  - ticker: AVEM
    value: 164.85
  - ticker: AVES
    value: 0.0
  - ticker: AVUV
    value: 193.87
  - ticker: AVDV
    value: 78.41

equities:
  DFUS:
    value_tilt: 0.0
    size_tilt: -0.02
    profitability_tilt: 0.05

    is_value: false
    region: US
    fractional: false
  DFAI:
    value_tilt: 0.08
    size_tilt: -0.18
    profitability_tilt: 0.02

    is_value: false
    region: Developed
    fractional: false
  AVEM:
    # Need to switch to AVES for more value tilt
    value_tilt: 0.03
    size_tilt: -0.01
    profitability_tilt: 0.19

    is_value: false
    region: Emerging
    fractional: true
  AVES:
    value_tilt: 0.18
    size_tilt: 0.32
    profitability_tilt: 0.17

    is_value: true
    region: Emerging
    fractional: true
  AVUV:
    value_tilt: 0.54
    size_tilt: 0.89
    profitability_tilt: 0.28

    is_value: true
    region: US
    fractional: true
  AVDV:
    value_tilt: 0.39
    size_tilt: 0.57
    profitability_tilt: 0.28

    is_value: true
    region: Developed
    fractional: true

target_value_split:
  US: 0.37
  Developed: 0.548
  Emerging: 1.0

